---

- hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
  - set_fact:
      template_path: "templates/interfaces.j2"
      config_path: "{{ inventory_dir }}/configs/{{ inventory_hostname }}.conf"

  - name: Build config from template
    template:
      src: "{{ template_path }}"
      dest: "{{ config_path }}"

  - name: Deploy config to Junos devices
    juniper_junos_config:
      host: "{{ inventory_hostname }}"
      load: update
      src: "{{ config_path }}"
      dest_dir: "{{ inventory_dir }}/config_change_logs"
      diff: true
      check: true
      commit: false
    register: pre_commit_result

  - name: proceed with config changes if needed
    import_tasks: commit_confirmed_tasks.yml
    when: pre_commit_result is changed
