---

- hosts: all
  connection: local
  gather_facts: no
  roles:
  - Juniper.junos

  vars_prompt:
  - name: username
    prompt: Enter username
    private: no

  - name: passwd
    prompt: Enter password
    private: yes
    confirm: no

  tasks:
  - set_fact:
      output_path: "output/"
      template_path: "templates/interfaces.j2"
      config_path: "configs/{{ inventory_hostname }}.conf"

  - name: Build config from template
    template:
      src: "{{ template_path }}"
      dest: "{{ config_path }}"

  - name: Deploy config to Junos devices
    juniper_junos_config:
      host: "{{ inventory_hostname }}"
      user: "{{ username }}"
      passwd: "{{ passwd }}"
      load: replace
      src: "{{ config_path }}"
      dest_dir: "{{ output_path }}"
      diff: true
      check: true
      commit: false
    register: pre_commit_result

  - name: proceed with config changes if needed
    import_tasks: commit_confirmed_tasks.yml
    when: pre_commit_result is changed
